name: Run

on:
  schedule:
    - cron: '0 0 * * MON' # https://crontab.guru/every-monday
  push:
    branches: [ master ]

jobs:

  run:
    name: Listar e renovar títulos pendentes
    runs-on: ubuntu-latest
    env:
      PERGAMUM_LOGIN: ${{ secrets.PERGAMUM_LOGIN }}
      PERGAMUM_PASSWORD: ${{ secrets.PERGAMUM_PASSWORD }}
      DEBUG: false

    steps:
    - uses: actions/checkout@v2
      if: success()

    - uses: actions/setup-node@v1
      if: success()
      with:
        node-version: '12.x'
    - name: Cache Node.js modules
      if: success()
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install NPM dependencies (using the lock file)
      run: npm ci --prod

    - name: Start
      if: success()
      run: npm start -- 'getTitulosPendentes | renovarTitulos'
